feat:  길드 생성 api
songpa-gu-people/good-game-server pull request #8
Opened 2022-10-02 14:35 UTC by ordinCode

2022-10-05 08:08 UTC, pci2676 requested changes
리뷰 달아뒀어! 시간날 때 한번 확인해줘~
일정 찍힌 회사일 때문에 내일 형이 대신하고 있어서 정말 미안하게 생각하구 있어 고마워 형 ㅠㅠ

2022-10-05 08:08 UTC, pci2676 commented on goodgame-api/src/main/kotlin/people/songpagu/goodgame/api/config/advice/ApiExceptionAdvice.kt
> +    fun methodArgumentNotValidException(e: MethodArgumentNotValidException): ApiResponse<Nothing> {
`Nothing`은 `throw`의 반환값이라고 생각하면 되기 때문에 여기에는 어울리지 않는것 같아~!

2022-10-05 08:08 UTC, pci2676 commented on goodgame-api/src/test/kotlin/people/songpagu/goodgame/api/acceptance/GuildAcceptanceTest.kt
> +        val transaction = getTransaction()
이거 레이지 로딩때문에 넣은건가??

2022-10-05 08:08 UTC, pci2676 commented on goodgame-api/src/test/kotlin/people/songpagu/goodgame/api/domain/guild/dto/request/GuildCreateRequestTest.kt
> +    @RepeatedTest(10)
10번 반복하는 이유가 있엉??

2022-10-05 08:08 UTC, pci2676 commented on goodgame-api/src/test/kotlin/people/songpagu/goodgame/api/domain/guild/dto/request/GuildCreateRequestTest.kt
> +    fun 이상_없는_dto() {
음 dto 레벨에 대한 valid 테스트가 독자적으로 있을때 큰 효용성이 있을지는 의문이야~!

2022-10-05 08:08 UTC, pci2676 commented on goodgame-domain/src/main/kotlin/people/songpagu/goodgame/domain/guild/type/GuildMemberPosition.kt
> +enum class GuildMemberPosition(
우리 지역이 들어가는 서비스라서 `Position`이라는 단어쓰면 나중에 혼동될 수 있을것 같은데 권한, 역할 같은 다른 단어를 사용하는거 별루얌?

2022-10-05 08:08 UTC, pci2676 commented on goodgame-persistence/rdb/src/main/kotlin/people/songpagu/goodgame/jpa/domain/guild/entity/GuildEntity.kt
> +        columnDefinition = "VARCHAR(${GUILD_NAME_MAX_LENGTH}) COMMENT '길드이름'"
오 이렇게 쓰면 일원화 가능하겠당 굳굳~!

2022-10-05 08:08 UTC, pci2676 commented on goodgame-domain/src/main/kotlin/people/songpagu/goodgame/domain/guild/type/GuildMemberPosition.kt
> +enum class GuildMemberPosition(
아 등급이라고 쓰고있구나 그럼 Position은 더 헷갈릴것 같지않아???

2022-10-05 08:08 UTC, pci2676 commented on goodgame-persistence/rdb/src/main/kotlin/people/songpagu/goodgame/jpa/domain/guild/entity/GuildEntity.kt
> +        columnDefinition = "VARCHAR(32) COMMENT '길드번호'"
엇 길드번호는 유니크하게 설정해두는게 좋지 않아??

2022-10-05 08:08 UTC, pci2676 commented on goodgame-persistence/rdb/src/main/kotlin/people/songpagu/goodgame/jpa/domain/guild/entity/GuildEntity.kt
> +    val guildMembers: MutableList<GuildMemberEntity>,
부모-자식 객체가 동일한 생명주기를 가지고 있지 않을때 OneToMany는 걷어내는게 좋다고 생각하는 편인데 어찌 생각해?

2022-10-05 08:08 UTC, pci2676 commented on goodgame-persistence/rdb/src/main/kotlin/people/songpagu/goodgame/jpa/domain/guild/entity/GuildMemberEntity.kt
> +    val guildEntity: GuildEntity,
길드id + 회원번호 두개 유니크 키로 관리해줘야 할것 같다고 생각해~!

2022-10-08 02:03 UTC, ordinCode commented on goodgame-api/src/test/kotlin/people/songpagu/goodgame/api/acceptance/GuildAcceptanceTest.kt
> +        val transaction = getTransaction()
응 맞아

2022-10-08 02:05 UTC, ordinCode commented on goodgame-api/src/main/kotlin/people/songpagu/goodgame/api/config/advice/ApiExceptionAdvice.kt
> +    fun methodArgumentNotValidException(e: MethodArgumentNotValidException): ApiResponse<Nothing> {
코틀린에서는 void 대신 nothing쓰는줄 알았는데 아니었구나 수정했어!

2022-10-08 02:08 UTC, ordinCode commented on goodgame-api/src/test/kotlin/people/songpagu/goodgame/api/domain/guild/dto/request/GuildCreateRequestTest.kt
> +    @RepeatedTest(10)
- 여러번 돌려도 시간적 차이가 없다
- 랜덤 요소가 테스트에 있다.

그래서 10번 돌려봤는데 애매하다 싶으면 한번돌려도 무관하다고 생각해

2022-10-08 02:14 UTC, ordinCode commented on goodgame-api/src/test/kotlin/people/songpagu/goodgame/api/domain/guild/dto/request/GuildCreateRequestTest.kt
> +    fun 이상_없는_dto() {
사실 처음에 아래와 같이 했다가
```kotlin
    @Size(max=10)
    val guildName: String,
```
validate가 안되길래 해결하는 과정에서 추가한 테스트였는데 지금은 지우는게 나을까?

2022-10-08 02:16 UTC, ordinCode commented on goodgame-domain/src/main/kotlin/people/songpagu/goodgame/domain/guild/type/GuildMemberPosition.kt
> +enum class GuildMemberPosition(
같은 생각이야 고민하다가 일단 했는데
Role이라 할까?

2022-10-08 02:17 UTC, ordinCode commented on goodgame-persistence/rdb/src/main/kotlin/people/songpagu/goodgame/jpa/domain/guild/entity/GuildEntity.kt
> +        columnDefinition = "VARCHAR(32) COMMENT '길드번호'"
@Table(
    name = "guild",
    uniqueConstraints = [
        UniqueConstraint(name = "uk_guild_1", columnNames = ["guild_number"]),
    ],
)
요렇게 설정해뒀어!
이렇게하면 유니크 되는거 맞지?

2022-10-08 02:22 UTC, ordinCode commented on goodgame-persistence/rdb/src/main/kotlin/people/songpagu/goodgame/jpa/domain/guild/entity/GuildEntity.kt
> +    val guildMembers: MutableList<GuildMemberEntity>,
연관관계를 끊자는 이야기지?

나도 고민이 됐던 부분인데, 
어떻게 보면 길드장이 길드를 생성하면서 Guild와 GuildMember가 생성은 동시에 되기도하고 둘은 도메인적으로도 강력하게 연관이 있어보여서 둘은 연관이 있는데 맞겠다 싶어

2022-10-08 02:23 UTC, ordinCode commented on goodgame-persistence/rdb/src/main/kotlin/people/songpagu/goodgame/jpa/domain/guild/entity/GuildMemberEntity.kt
> +    val guildEntity: GuildEntity,
길드id + 회원번호 복합키로 하자는 이야기지?

2022-10-08 08:28 UTC, pci2676 commented on goodgame-api/src/test/kotlin/people/songpagu/goodgame/api/domain/guild/dto/request/GuildCreateRequestTest.kt
> +    @RepeatedTest(10)
랜덤요소에 대한 테스트가 의미가 있나가 가장 큰 문제인거같거든 10번정도 돌리면 모든케이스가 다 걸리지 않을까 이런느낌인데 이게 불확실성을 테스트하는거라 비즈니스적으로 의미가 없는것 같아
나는 랜덤요소에 대해서는 굳이 테스트를 안해도 될것같아~!

2022-10-08 08:29 UTC, pci2676 commented on goodgame-api/src/test/kotlin/people/songpagu/goodgame/api/domain/guild/dto/request/GuildCreateRequestTest.kt
> +    fun 이상_없는_dto() {
이미 있는건 둬도 될 것 같아 근데 매번 추가하기는 조금 부담스러울것 같아서 ㅎㅎ

2022-10-08 08:29 UTC, pci2676 commented on goodgame-domain/src/main/kotlin/people/songpagu/goodgame/domain/guild/type/GuildMemberPosition.kt
> +enum class GuildMemberPosition(
나는 롤이 더 좋은거같아 ㅎㅎ

2022-10-08 08:29 UTC, pci2676 commented on goodgame-persistence/rdb/src/main/kotlin/people/songpagu/goodgame/jpa/domain/guild/entity/GuildEntity.kt
> +        columnDefinition = "VARCHAR(32) COMMENT '길드번호'"
마자마자!

2022-10-08 08:31 UTC, pci2676 commented on goodgame-persistence/rdb/src/main/kotlin/people/songpagu/goodgame/jpa/domain/guild/entity/GuildEntity.kt
> +    val guildMembers: MutableList<GuildMemberEntity>,
생성될때는 같이 생성될수 있지만
제거되거나 추가될때를 생각해보면 길드멤버가 길드와 같은 생명주기를 갖게된다고 볼 수 없는것 같아서~!
가능하면 단지 연관관계 때문에 추가하는거보다 완벽하게 같은 생명주기를 같게될때 사용하는게 좋다고 생각하는 편이거든~!
근데 편의성을 위해서라면야 뭐~! 그냥 이야기를 해보고싶었엉~!!

2022-10-08 08:31 UTC, pci2676 approved these changes

2022-10-08 10:13 UTC, merged